services:
 # 1. SERVER DATABASE
  mysql-server:
    image: mysql:8.0-debian
    container_name: Alat_API-DB
    restart: always
    environment:
      MYSQL_DATABASE: Alat_API
      MYSQL_USER: alat_api
      MYSQL_PASSWORD: alat_api
      MYSQL_ROOT_PASSWORD: passwordroot
    ports:
      - "3306:3306"
    networks:
      - Peminjaman-Alat
    volumes:
      - db_data:/var/lib/mysql

  # 2 SERVER BACKEND (LARAVEL)
  app-laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Alat_app
    user: "1000:1000"
    working_dir: /var/www
    ports:
      - "8082:8000"
    volumes:
      - ./backend:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000 --no-reload
    depends_on:
      - mysql-server
    networks:
      - Peminjaman-Alat

  # 3. SERVER UI DATABASE (PHPMYADMIN)
  phpMyadmin:
    image: phpmyadmin
    container_name: phpMyadmin-Alat
    restart: always
    environment:
      PMA_HOST: mysql-server
    ports:
      - "8081:80"
    depends_on:
      - mysql-server
    networks:
      - Peminjaman-Alat

volumes:
  db_data:
networks:
  Peminjaman-Alat:
    driver: bridge
